 opts = {
    ensure_installed = {
      "vim",
      "lua",
      "vimdoc",
      "html",
      "css",
      "javascript",
      "typescript",
      "json",
      "jsonc",
      "tsx",
      "markdown",
      "markdown_inline",
      "c",
      "cpp",
      "rust",
      "python",
      "bash",
      "yaml",
      "toml",
      "cmake",
      "make",
      "dockerfile",
      "gitignore",
      "go",
      "sql",
      "java",
      "terraform",
      "hcl",
      "prisma",
      "groovy",
    },
    highlight = { enable = true },
    indent = { enable = true },
  }
